//
//  ClipboardMonitor.swift
//  MacOsClipBoard
//
//  Watches the system pasteboard and records new text clips.
//
//  Cost control — this runs for the whole login session, so it must stay near-free:
//
//  * macOS has no pasteboard-change notification. Polling `changeCount` is the only
//    supported approach. That read is a cheap IPC round-trip to the pasteboard
//    server; the *contents* are only read on the rare tick where the count moved.
//  * The timer carries a large `tolerance`, which lets macOS coalesce our wakeups
//    with other timers rather than waking an idle CPU on our schedule. This is the
//    single biggest battery factor for a background poller.
//  * Polling stops entirely while the machine is asleep.
//

import AppKit
import Foundation
import Observation
import OSLog
import SwiftData

@MainActor
@Observable
final class ClipboardMonitor {
    /// Fast enough to feel instant, slow enough to disappear into timer coalescing.
    static let pollInterval: TimeInterval = 0.5
    /// Lets macOS slide any given tick by up to this much to batch CPU wakeups.
    static let pollTolerance: TimeInterval = 0.25
    /// Clips larger than this are ignored rather than bloating the store. A copied
    /// log file or minified bundle is not something anyone pastes from history.
    static let maxClipCharacters = 256_000

    /// Markers a source app sets to say "do not record this". Password managers use
    /// the concealed type; honoring these is a correctness requirement, not a nicety.
    private static let ignoredTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]

    private static let log = Logger(subsystem: "kimsinh.MacOsClipBoard", category: "monitor")

    private(set) var isRunning = false
    private(set) var capturedCount = 0

    private let store: ClipStore
    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount
    private var sleepObservers: [NSObjectProtocol] = []

    init(store: ClipStore) {
        self.store = store
    }

    // MARK: - Lifecycle 
    func start() {
        guard !isRunning else { return }
        isRunning = true
        lastChangeCount = NSPasteboard.general.changeCount
        scheduleTimer()
        observeSleepWake()
        Self.log.notice("monitor started")
    }

    func stop() {
        isRunning = false
        timer?.invalidate()
        timer = nil
    }

    private func scheduleTimer() {
        timer?.invalidate()
        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { _ in
            // Timers scheduled on the main run loop fire on the main actor.
            MainActor.assumeIsolated { self.poll() }
        }
        timer.tolerance = Self.pollTolerance
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func observeSleepWake() {
        guard sleepObservers.isEmpty else { return }
        let center = NSWorkspace.shared.notificationCenter
        // Nothing can be copied while the machine is asleep, so stop burning ticks.
        sleepObservers.append(
            center.addObserver(forName: NSWorkspace.willSleepNotification, object: nil, queue: .main) { _ in
                MainActor.assumeIsolated { self.timer?.invalidate(); self.timer = nil }
            }
        )
        sleepObservers.append(
            center.addObserver(forName: NSWorkspace.didWakeNotification, object: nil, queue: .main) { _ in
                MainActor.assumeIsolated {
                    guard self.isRunning else { return }
                    // Anything copied across the sleep boundary is already gone; just resync.
                    self.lastChangeCount = NSPasteboard.general.changeCount
                    self.scheduleTimer()
                }
            }
        )
    }

    // MARK: - Polling

    private func poll() {
        let pasteboard = NSPasteboard.general
        let changeCount = pasteboard.changeCount
        guard changeCount != lastChangeCount else { return }
        lastChangeCount = changeCount

        guard !isConcealed(pasteboard) else { return }
        guard let text = pasteboard.string(forType: .string) else { return }
        guard text.count <= Self.maxClipCharacters else { return }

        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        if store.record(text, sourceBundleID: source) != nil {
            capturedCount += 1
        }
    }

    private func isConcealed(_ pasteboard: NSPasteboard) -> Bool {
        guard let types = pasteboard.types else { return false }
        return types.contains { Self.ignoredTypes.contains($0.rawValue) }
    }

    // MARK: - Writing

    /// Puts a clip back on the pasteboard. Routing writes through here keeps the app
    /// from re-capturing its own paste as a brand new clip.
    func write(_ clip: Clip) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(clip.content, forType: .string)
        lastChangeCount = pasteboard.changeCount
        store.markUsed(clip)
    }

    /// Manual capture, used by the UI until the panel and hotkey exist.
    @discardableResult
    func captureCurrentPasteboard() -> Clip? {
        let pasteboard = NSPasteboard.general
        guard !isConcealed(pasteboard), let text = pasteboard.string(forType: .string) else { return nil }
        lastChangeCount = pasteboard.changeCount
        return store.record(text, sourceBundleID: NSWorkspace.shared.frontmostApplication?.bundleIdentifier)
    }
}
